# https://taskfile.dev

version: '3'

tasks:
  act-build:
    cmds:
      - act -W .github/workflows/build.yaml

  act-install:
    cmds:
      - act -W .github/workflows/install.yaml
      -
  act-test:
    cmds:
      - act -W .github/workflows/test.yaml
\